# Generated by Django 4.2.15 on 2024-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("property_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=50),
                ),
                (
                    "price_per_month",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=50),
                ),
                ("negotiable", models.BooleanField(default=False)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("square_size", models.IntegerField(blank=True, null=True)),
                ("lot_size", models.FloatField(blank=True, null=True)),
                ("garage", models.BooleanField(default=False)),
                ("swimming_pool", models.BooleanField(default=False)),
                ("boys_quarters", models.BooleanField(default=False)),
                ("furnished", models.BooleanField(default=False)),
                (
                    "furnished_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NF", "Not Furnished"),
                            ("SF", "Semi Furnished"),
                            ("FF", "Fully Furnished"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="property_videos/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="Listing.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_pictures/")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="Listing.listing",
                    ),
                ),
            ],
        ),
    ]
