# Generated by Django 5.0.6 on 2024-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="furnished_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FF", "Fully Furnished"),
                    ("SF", "Semi Furnished"),
                    ("NF", "Not Furnished"),
                ],
                max_length=20,
            ),
        ),
    ]
