# Generated by Django 4.2.14 on 2024-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Housing",
            fields=[
                ("property_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("MLS_no", models.CharField(max_length=15)),
                ("exterior_acre", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
