# Generated by Django 5.0.6 on 2024-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_password", models.CharField(max_length=30)),
                ("new_password", models.CharField(max_length=30)),
                ("confirm_password", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="Housing",
        ),
    ]
